project:
  type: website
  output-dir: _site

website:
  title: "Anthology of Data Science"
  site-url: https://anthology-of-data.science
  repo-url: https://github.com/dkapitan/anthology-of-data-science
  repo-actions: [issue]
  reader-mode: true
  search:
    location: sidebar
    type: textbox
  sidebar:
    title: false
    logo: /logo-anthology-of-data-science.png    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/dkapitan/
        text: "LinkedIn profile"
      - icon: github
        href: https://github.com/dkapitan
        text: "GitHub profile"
    style: floating
    collapse-level: 1
    contents:
      - section: Books
        href: books.qmd
        contents:
          - text: "Introduction to Statistical Learning"
            href: books/islp.qmd
          - text: "Python for Data Analysis"
            href: books/pda.qmd
          - text: "R for Data Science"
            href: books/r4ds.qmd
          - text: "Interpretable ML"
            href: books/iml.qmd
          - text: "Time-series forecasting"
            href: books/fpp.qmd
          - text: "Deep Learning"
            href: books/udl.qmd
          - text: "The Turing Way"
            href: books/turing-way.qmd
      - section: Getting into Python
        href: python/index.qmd
        contents:
          - text: "Real Python"
            href: python/realpython.qmd
          - text: "Tour of Python"
            href: python/whirlwind.qmd
          - text: "Pythonic and idiomatic Python"
            href: python/effective-python-and-idiomatic-pandas.ipynb
      - section: Visualization with Altair
        href: altair/index.qmd
        contents: altair/*
      - section: "Selected articles"
        href: posts/index.qmd
        contents: posts/*/*
      - section: "Use cases"
        href: cases/index.qmd
        contents: posts/*/*
      - section: "Notebooks"
        href: notebooks/index.qmd
        contents: notebooks/*/*
  page-footer:
    left: |
      <br>
      © 2023 by Daniel Kapitan<br>
      This website was created with [![](/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)<br>
      [![](/cc-by-nc-eu.png){fig-alt="CC BY-NC 4.0"}](http://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1)<br>

format:
  html:
    theme:
      - cosmo
      - mozilla.scss
    css: styles.css
    toc: true

execute:
  freeze: auto  # re-render only when source changes

